server:
  port: 8769
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuteLittleMango/learn.git # 配置git仓库的地址
          search-paths: springcloud/config-repo                              # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: shenmin881101@163.com                               # git仓库的账号
          password: shenmin881101
